### ISSUE TITLE
Cannot build with stable 1.17.2

### ISSUE THREAD

**Issue by StephanCassel** [dlutton/flutter_tts#117]
Cannot build with stable 1.17.2
**It worked fine with v1.12.13+hotfix.8**

 /Users/stephan/development/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_tts-1.2.0/ios/Classes/FlutterTtsPlugin.m:4:17: error: definition of 'FlutterTtsPlugin' must be imported from module 'flutter_tts.FlutterTtsPlugin' before it is required
    @implementation FlutterTtsPlugin

[✓] Flutter (Channel stable, v1.17.2, on Mac OS X 10.15.5 19F101, locale en-NO)
    • Flutter version 1.17.2 at /Users/stephan/development/flutter
    • Framework revision 5f21edf8b6 (5 days ago), 2020-05-28 12:44:12 -0700
    • Engine revision b851c71829
    • Dart version 2.8.3

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/stephan/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.3

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] Connected device (1 available)
    • Stephan’s iPad pro • 9bd45e81b7366db827aba7a7ab7d56432329e4cd • ios • iOS 13.4.1

• No issues found!
Process finished with exit code 0

**Comment by StephanCassel** [comment]
Sorry. It was a missing bridge-header. Works like a charm.
