### ISSUE TITLE
'setCategory' is unavailable in Swift / AVAudioSessionCategoryPlayback' has been renamed to 'AVAudioSession.Category.playback'

### ISSUE THREAD

**Issue by ashihCT** [dlutton/flutter_tts#25]
## 🐛 Bug Report

/Users/user/Downloads/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_tts-0.2.3/ios/Classes/SwiftFlutterTtsPlugin.swift:23:43: error: 'setCategory' is unavailable in Swift
          try AVAudioSession.sharedInstance().setCategory(AVAudioSessionCategoryPlayback)
                                              ^~~~~~~~~~~
    AVFoundation.AVAudioSession:23:15: note: 'setCategory' has been explicitly marked unavailable here
        open func setCategory(_ category: AVAudioSession.Category) throws
                  ^
    /Users/user/Downloads/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_tts-0.2.3/ios/Classes/SwiftFlutterTtsPlugin.swift:23:55: error: 'AVAudioSessionCategoryPlayback' has been renamed to 'AVAudioSession.Category.playback'
          try AVAudioSession.sharedInstance().setCategory(AVAudioSessionCategoryPlayback)
                                                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                                          AVAudioSession.Category.playback
    AVFoundation.AVAudioSessionCategoryPlayback:3:12: note: 'AVAudioSessionCategoryPlayback' was obsoleted in Swift 3
    public let AVAudioSessionCategoryPlayback: AVAudioSession.Category
               ^

**Version:** 0.2.3

**Platform:** 
- [ X] :iphone: iOS
- [ ] :robot: Android

**Comment by dlutton** [comment]
Thanks for reporting this issue @ashihCT, which swift version are you using?

**Comment by ashihCT** [comment]
I am using Swift 4.2. Unfortunately due to other plugins that require 4.2, I cannot downgrade to 4.0.

**Comment by dlutton** [comment]
Thanks @ashihCT, I'm sure it's related to the last update I made to allow the voice to work with the switch set to silent.  I'll need to look into implementing a fix for the latest swift version (there is a known [issue](http://www.openradar.me/42382075)).  version 0.2.2 of this plugin should work for you if you don't need that feature until I can implement a fix.

**Comment by ashihCT** [comment]
@dlutton  Thanks for setting me on the right path! I rolled back to 0.2.1 and the issue is gone.
Hope to see a fix in the near future! :)

**Comment by dlutton** [comment]
@ashihCT my apologies I meant 0.2.1.  I'll research a fix soon

**Comment by ukrx-xamd** [comment]
This works for me with SWIFT_VERSION=4.0 and use_frameworks! with version 0.2.3. I had the initial :

setCategory' is unavailable in Swift

But that was because I had an Obj-C oriented project. I added bridging support and the issue went away.

**Comment by dlutton** [comment]
@ukrx-xamd Thanks for the information just in case others encounter a similar issue, however this is still an issue with SWIFT_VERSION=4.2.

**Comment by JonasJW** [comment]
@dlutton I tried 0.2.1 and it doesn't work either for me.

**Comment by dlutton** [comment]
@JonasJW what exactly doesn't work on 0.2.1?  Is there an error message you can provide along with the swift version you're using?

Thank you!

**Comment by JonasJW** [comment]
Sorry, I was refering to your answer to ashihCT where you said version 0.2.1 should work. However this version isn't working for me. I get the exact same error as reported. I'm using Swift 4.2.

I just read version 0.2.1 is working for ashihCT. Thats wierd because it isn't working for me.

**Comment by dlutton** [comment]
@JonasJW you shouldn't be receiving that error using 0.2.1 since `setCategory` wasn't added until later.  You may need to run flutter clean in your project's root folder.

**Comment by JonasJW** [comment]
The problem was I was using ^0.2.1 instead of just 0.2.1. However with version 0.2.1 I get this error:
```
/Users/jonas/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_tts-0.2.1/ios/Classes/FlutterTtsPlugin.m:2:9: fatal error: 'flutter_tts/flutter_tts-Swift.h' file not found
    #import <flutter_tts/flutter_tts-Swift.h>
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    1 error generated.
```

Any Idea about this one?

**Comment by dlutton** [comment]
@JonasJW that error sounds like it might be related to : [issue 7](https://github.com/dlutton/flutter_tts/issues/7)

**Comment by ngocdaothanh** [comment]
Flutter now uses Swift 4.0 by default, so I think you can now update the code.

After updating Swift in my project to 4.2 (so that I can use https://github.com/rxlabz/speech_recognition):

```
Xcode's output:
↳
    === BUILD TARGET url_launcher OF PROJECT Pods WITH CONFIGURATION Debug ===
    <unknown>:0: warning: imported declaration 'UITableViewDiffableDataSourceCellProvider' could not be mapped to 'UITableViewDiffableDataSourceReference.CellProvider'
    <unknown>:0: warning: imported declaration 'UICollectionViewDiffableDataSourceCellProvider' could not be mapped to 'UICollectionViewDiffableDataSourceReference.CellProvider'
    /Users/ndao/opt/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_tts-0.2.6/ios/Classes/SwiftFlutterTtsPlugin.swift:24:55: error: 'AVAudioSessionCategoryPlayback' has been renamed to 'AVAudioSession.Category.playback'
          try AVAudioSession.sharedInstance().setCategory(AVAudioSessionCategoryPlayback)
                                                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                                          AVAudioSession.Category.playback
    AVFoundation.AVAudioSessionCategoryPlayback:3:12: note: 'AVAudioSessionCategoryPlayback' was obsoleted in Swift 3
    public let AVAudioSessionCategoryPlayback: AVAudioSession.Category
               ^

Could not build the application for the simulator.
```

I had to manually modify `SwiftFlutterTtsPlugin.swift` on my local machine.

**Comment by aimensasi** [comment]
this is still an issue even in `flutter_tts: ^0.2.6`

```
flutter_tts-0.2.6/ios/Classes/SwiftFlutterTtsPlugin.swift:24:55: error: 'AVAudioSessionCategoryPlayback' has been renamed to 'AVAudioSession.Category.playback'
          try AVAudioSession.sharedInstance().setCategory(AVAudioSessionCategoryPlayback)
                                                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                                          AVAudioSession.Category.playback
    AVFoundation.AVAudioSessionCategoryPlayback:3:12: note: 'AVAudioSessionCategoryPlayback' was obsoleted in Swift 3
    public let AVAudioSessionCategoryPlayback: AVAudioSession.Category
```

**Comment by dlutton** [comment]
correct @aimensasi I haven't made any changes in this plugin regarding this issue, however per the issue reported in [stackoverflow](https://stackoverflow.com/questions/51010390/avaudiosession-setcategory-swift-4-2-ios-12-play-sound-on-silent), this method should now work in Xcode 10.2 since the method has been added again.  When I get some time I'll try to play around with it to see if it works or if I need to add additional code.

**Comment by iPatel007** [comment]
I got same issue but I resolved it by manually added library to my app.

-> download this project "flutter_tts" and delete "example" folder
-> Move "flutter_tts" to your project repository 
-> Update 'pubspec.yaml' of your project like below 


```

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_tts:
    path: ./flutter_tts-master
```

-> Set setting for Android/iOS configuration as per mention in **Readme**

That's it.

**Comment by dlutton** [comment]
this should now be resolved with the latest version.

**Comment by ryanheise** [comment]
Hi @dlutton , I'm using is a late 2013 model MacBook Pro which unfortunately does not allow me to install a version of Xcode higher than 10.1, and I noticed that the solution you implemented only works from Xcode 10.2. Is there any chance you could use the workaround mentioned in https://stackoverflow.com/a/52396244 ?

**Comment by dlutton** [comment]
@ryanheise sure I'll look into implementing that.

**Comment by nguyenlinhnttu** [comment]
flutter_tts 0.8.5 not working on ios.  it same issues.

**Comment by dlutton** [comment]
@nguyenlinhnttu what version of xcode are you using?

**Comment by nguyenlinhnttu** [comment]
@dlutton I use Xcode version 10.1 maybe it old and not supported. Because mac mini can't upgrade :D

**Comment by dlutton** [comment]
@nguyenlinhnttu is this still an issue?

**Comment by dlutton** [comment]
is this still an issue @ashihCT ?
